### ISSUE TITLE
Hotspot can be turned off while in use

### ISSUE THREAD

**Issue by lrnselfreliance** [lrnselfreliance/wrolpi#173]
A User can accidentally turn off the hotspot by clicking the Wifi icon in the navbar even when users are on the hotspot.

There are two possible solutions:
- Refuse to turn off the hotspot when DHCP addresses are in use on the hotspot.
  - It could be useful to continually ping each address on the hotspot and display how devices are connected.
- Refuse to turn off the hotspot if the ethernet port disconnected.

**Comment by electromage** [comment]
I don't think it should refuse, but a simple warning might be good. The owner of the device may have good reason to disable the hotspot without having to power-off or disconnect clients first.

**Comment by lrnselfreliance** [comment]
> I don't think it should refuse, but a simple warning might be good. The owner of the device may have good reason to disable the hotspot without having to power-off or disconnect clients first.

Great point. I think it would be best to simply add a confirmation modal when the Wifi icon is clicked.
