### ISSUE TITLE
When changing navbar color search icon does not change to match

### ISSUE THREAD

**Issue by mattriney** [lrnselfreliance/wrolpi#276]
Wrolpi v14.0
Debian

![image](https://github.com/user-attachments/assets/e1b08db6-b059-4db8-95cf-c54f7e5c8434)

**Comment by lrnselfreliance** [comment]
This is caused because the search icon here is a literal Button.  This should probably be fixed by converting this to just an Icon, but with an `onClick`.

**Comment by lrnselfreliance** [comment]
Fixed in 0f003a6dc1feb0e3bfb81744df157495b0583ff4
